apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels: 
    app: clientApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clientApp
  template:
    metadata:
      labels:
        app: clientApp
    spec:
      containers:
      - name: client-trello
        image: jomadotio/my-trello:v1
        ports:
        - containerPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: clientApp
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
  type: NodePort
