apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-microservice-deployment
  labels: 
    app: commentsService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commentsService
  template:
    metadata:
      labels:
        app: commentsService
    spec:
      containers:
      - name: user-microservice
        image: jomadotio/comments_microservice:v1
        ports:
        - containerPort: 3002
        resources:
          requests: 
            memory: "50Mi"
            cpu: "200m"
          limits:
            memory: "200Mi"
            cpu: "1000m"
          

---

apiVersion: v1
kind: Service
metadata:
  name: comments-service
spec:
  selector:
    app: commentsService
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
  type: LoadBalancer

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: comments-microservice-deployment-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: comments-microservice-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 1
